# Generated by Django 4.2.4 on 2023-10-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tercera_Pre_Entrega_Paal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='Libros'),
        ),
    ]
