# Generated by Django 4.2.4 on 2023-09-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tercera_Pre_Entrega_Paal', '0002_consulta_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='precio',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='precio',
            field=models.CharField(max_length=40),
        ),
    ]
