# Generated by Django 4.2.4 on 2023-09-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tercera_Pre_Entrega_Paal', '0003_alter_libro_precio_alter_merchandising_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas_Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Tercera_Pre_Entrega_Paal.consulta')),
            ],
        ),
    ]
