# Generated by Django 4.2.4 on 2023-09-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tercera_Pre_Entrega_Paal', '0004_consultas_usuarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandising',
            options={'verbose_name_plural': 'Merchandising'},
        ),
        migrations.AlterModelOptions(
            name='novedad',
            options={'verbose_name_plural': 'Novedades'},
        ),
    ]
