# Generated by Django 4.2.4 on 2023-10-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tercera_Pre_Entrega_Paal', '0004_libro_creacion_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandising',
            name='creacion',
            field=models.CharField(default='2023/10/03', max_length=50),
        ),
        migrations.AddField(
            model_name='novedad',
            name='creacion',
            field=models.CharField(default='2023/10/03', max_length=50),
        ),
    ]
