# Generated by Django 4.2.4 on 2023-09-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tercera_Pre_Entrega_Paal', '0005_alter_merchandising_options_alter_novedad_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultas_Usuarios',
            new_name='Consultas_Clientes',
        ),
        migrations.RenameField(
            model_name='consultas_clientes',
            old_name='consulta_usuario',
            new_name='consulta_cliente',
        ),
    ]
