# Generated by Django 4.2.4 on 2023-10-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tercera_Pre_Entrega_Paal', '0005_merchandising_creacion_novedad_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchandising',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
