# Generated by Django 4.2.4 on 2023-10-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tercera_Pre_Entrega_Paal', '0007_alter_libro_creacion_alter_merchandising_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='texto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
