# Generated by Django 4.2.4 on 2023-09-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tercera_Pre_Entrega_Paal', '0008_staff_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='merchandising',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='novedad',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
