# Generated by Django 4.2.4 on 2023-09-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tercera_Pre_Entrega_Paal', '0009_libro_imagen_merchandising_imagen_novedad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Libros'),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Merchandising'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Novedades'),
        ),
    ]
