# Generated by Django 4.2.4 on 2023-09-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tercera_Pre_Entrega_Paal', '0011_rename_nombre_merchandising_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchandising',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
